options(stringsAsFactors = F)

bbc1 <- read.delim("/Users/clunch/Desktop/UserActivityEdits/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")
bbc2 <- read.delim("/Users/clunch/Desktop/UserActivityEdits 2/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")
bbc3 <- read.delim("/Users/clunch/Desktop/UserActivityEdits 3/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")
bbc4 <- read.delim("/Users/clunch/Desktop/UserActivityEdits 4/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")
bbc5 <- read.delim("/Users/clunch/Desktop/UserActivityEdits 5/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")
bbc6 <- read.delim("/Users/clunch/Desktop/UserActivityEdits 6/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")
bbc7 <- read.delim("/Users/clunch/Desktop/UserActivityEdits 7/NEON.DOM.SITE.DP0.10067.001:bbc_percore_in/parserActivities.txt", sep="\t")

length(which(bbc1$uid %in% bbc2$uid))
length(which(bbc1$uid %in% bbc3$uid))
length(which(bbc2$uid %in% bbc3$uid))
length(which(bbc1$uid %in% bbc4$uid))
length(which(bbc2$uid %in% bbc4$uid))
length(which(bbc3$uid %in% bbc4$uid))
length(which(bbc1$uid %in% bbc5$uid))
length(which(bbc2$uid %in% bbc5$uid))
length(which(bbc3$uid %in% bbc5$uid))
length(which(bbc4$uid %in% bbc5$uid))
length(which(bbc1$uid %in% bbc6$uid))
length(which(bbc2$uid %in% bbc6$uid))
length(which(bbc3$uid %in% bbc6$uid))
length(which(bbc4$uid %in% bbc6$uid))
length(which(bbc5$uid %in% bbc6$uid))
length(which(bbc1$uid %in% bbc7$uid))
length(which(bbc2$uid %in% bbc7$uid))
length(which(bbc3$uid %in% bbc7$uid))
length(which(bbc4$uid %in% bbc7$uid))
length(which(bbc5$uid %in% bbc7$uid))
length(which(bbc6$uid %in% bbc7$uid))
# all 0

bbc.fail <- read.delim("/Users/clunch/Desktop/Root_sampling_tower_plots,_Level_0_bbc_percore_in - chunk 1 - failed.txt", sep="\t")
length(which(bbc.fail$uid %in% bbc1$uid))
length(which(bbc.fail$uid %in% bbc2$uid))
length(which(bbc.fail$uid %in% bbc3$uid))
length(which(bbc.fail$uid %in% bbc4$uid))
length(which(bbc.fail$uid %in% bbc5$uid))
length(which(bbc.fail$uid %in% bbc6$uid))
length(which(bbc.fail$uid %in% bbc7$uid))

length(which(bbc5$sampleID %in% bbc6$sampleID))
length(which(bbc5$sampleID %in% bbc7$sampleID))
length(which(bbc6$sampleID %in% bbc7$sampleID))

#a4565f96-c83a-4985-b18a-d114a5638a42
