library(devtools)
install(".")
library(neonUtilities)
zipsByProduct(dpID="DP4.00131.001", package="expanded", savepath="/Users/clunch/Desktop")
stackByTable("/Users/clunch/Desktop/filesToStack00131", folder=T)
zipsByURI("/Users/clunch/Desktop/filesToStack00131/stackedFiles")

zipsByProduct(dpID="DP1.10081.001", package="expanded", savepath="/Users/clunch/Desktop")
stackByTable("/Users/clunch/Desktop/filesToStack10081", folder=T)
zipsByURI("/Users/clunch/Desktop/filesToStack10081/stackedFiles")
