---
title: "NEON Data Product Catalog"
output: pdf_document
---

```{r setup, include=FALSE}

library(httr)
library(jsonlite)
library(dplyr, quietly=T)
library(devtools)
req <- GET("http://data.neonscience.org/api/v0/products")
prod.list <- fromJSON(content(req, as="text"), simplifyDataFrame=T, flatten=T)
prod.frm <- prod.list[[1]]
prod.frm <- prod.frm[order(prod.frm$productName),]
prod.frm <- prod.frm[-grep("IP", prod.frm$productCode),]

ind <- grep("*Note", prod.frm$productAbstract)
for(j in ind) {
  prod.frm$productAbstract[j] <- substring(prod.frm$productAbstract[j], 
                                           1,
                                           regexpr("*Note", prod.frm$productAbstract[j])[1]-2)
}

```

```{r per_product, echo=F, results='asis'}

dd <- iconv(prod.frm$productDesignDescription, from="UTF-8", to="ASCII", sub="byte")
stud <- iconv(prod.frm$productStudyDescription, from="UTF-8", to="ASCII", sub="byte")
sen <- iconv(prod.frm$productSensor, from="UTF-8", to="ASCII", sub="byte")

sc.convert <- read.delim("/Users/clunch/sandbox/sc_markdown_convert.txt", sep="\t")
colnames(sc.convert) <- c("bytes","md")
for(k in sc.convert$bytes) {
  ind <- grep(k, dd)
  dd[ind] <- gsub(k, sc.convert$md[which(sc.convert$bytes==k)], dd[ind])
  ind.s <- grep(k, stud)
  stud[ind.s] <- gsub(k, sc.convert$md[which(sc.convert$bytes==k)], stud[ind.s])
  ind.n <- grep(k, sen)
  sen[ind.n] <- gsub(k, sc.convert$md[which(sc.convert$bytes==k)], sen[ind.n])
}

for(i in 1:nrow(prod.frm)) {
  
  cat("\\newpage", fill=T)
  cat(" ", "\n", fill=T)
  cat("#", prod.frm$productCode[i], prod.frm$productName[i], sep=" ", fill=T)
  #cat("\n", "----------------------", fill=T)
  cat("\n", "**Subsystem**", sep=" ", fill=T)
  cat("\n", prod.frm$productScienceTeam[i], sep=" ", fill=T)
  
  if(!is.na(sen[i])) {
    #cat("\n", "----------------------", fill=T)
    cat("\n", "**Sensor**", sep=" ", fill=T)
    cat("\n", sen[i], sep=" ", fill=T)
  }

  #cat("\n", "----------------------", fill=T)
  cat("\n", "**Coverage**", sep=" ", fill=T)
  cat("\n", stud[i], sep=" ", fill=T)
  #cat("\n", "----------------------", fill=T)
  cat("\n", "**Description**", sep=" ", fill=T)
  cat("\n", prod.frm$productDescription[i], sep=" ", fill=T)
  #cat("\n", "----------------------", fill=T)
  cat("\n", "**Abstract**", sep=" ", fill=T)
  cat("\n", prod.frm$productAbstract[i], sep=" ", fill=T)
  
  #cat("\n", "----------------------", fill=T)
  cat("\n", "**Design Description**", sep=" ", fill=T)
  cat("\n", dd[i], sep=" ", fill=T)

  # if(!is.na(prod.frm$productRemarks[i])) {
  #   cat("\n", "----------------------", fill=T)
  #   cat("\n", "**Usage Notes**", sep=" ", fill=T)
  #   cat("\n", prod.frm$productRemarks[i], sep=" ", fill=T)
  # }


  # which(nchar(prod.frm$productDesignDescription, type="char")!=
  #   nchar(prod.frm$productDesignDescription, type="bytes"))
  # which(nchar(prod.frm$productSensor, type="char")!=
  #   nchar(prod.frm$productSensor, type="bytes"))
  # which(nchar(prod.frm$productStudyDescription, type="char")!=
  #   nchar(prod.frm$productStudyDescription, type="bytes"))
  
}

```

