library(httr)
library(jsonlite)
req <- GET("https://cert-data.ci.neoninternal.org/api/v0/locations/")
req <- GET("https://cert-data.ci.neoninternal.org/api/v0/locations/SOILPL100213?history=true")
fromJSON(content(req, as="text"))
req <- GET("https://cert-data.ci.neoninternal.org/api/v0/locations/SOILPL104735?history=true")
fromJSON(content(req, as="text"))
req <- GET("https://cert-data.ci.neoninternal.org/api/v0/locations/HOPB.AOS.gauge?history=true")
fromJSON(content(req, as="text"))
req <- GET("https://cert-data.ci.neoninternal.org/api/v0/locations/CFGLOC101489?history=true")
fromJSON(content(req, as="text"))
